name: "Check HLD documents content"
on:
  pull_request:
    types: [opened,edited,synchronize]

jobs:
  changed_files:
    runs-on: ubuntu-latest
    name: Test changed-files
    permissions:
      pull-requests: read

    steps:
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40

      - name: Checkout
        uses: actions/checkout@v3

      - name: Verify all the HLD files
        run: |
          search_words=("Overview" "Functional requirements" "Non-functional requirements" "Solution" "Involved flows")
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [[ "$file" =~ \.MD$ ]]; then
              echo "$file verification..."
              all_present=true
              for word in "${search_words[@]}"; do
                if ! grep -q "$word" "${{ github.workspace }}/$file"; then
                  all_present=false
                  break
                fi
              done
      
              if [ "$all_present" = true ]; then
                echo "File '$file' passes validation."
              else
                echo "File '$file' does not pass validation."
                exit 1
              fi
            fi
          done